export const ContentProductData = [
    {
        imgUrl: "./assets/images/content_product1.png",
        heading: "Dictum morbi",
        cPrice: "$26.00",
        sPrice: "$52.00",
        stars: ["./assets/images/star.png", "./assets/images/star.png", "./assets/images/star.png",  "./assets/images/star.png", "./assets/images/star-dark.png"],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        imgUrl: "./assets/images/content_product2.png",
        heading: "Sodales sit",
        cPrice: "$26.00",
        sPrice: "$52.00",
        stars: ["./assets/images/star.png", "./assets/images/star.png", "./assets/images/star.png",  "./assets/images/star.png", "./assets/images/star-dark.png"],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        imgUrl: "./assets/images/content_product3.png",
        heading: "Nibh varius",
        cPrice: "$26.00",
        sPrice: "$52.00",
        stars: ["./assets/images/star.png", "./assets/images/star.png", "./assets/images/star.png",  "./assets/images/star.png", "./assets/images/star-dark.png"],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        imgUrl: "./assets/images/content_product4.png",
        heading: "Mauris quis",
        cPrice: "$26.00",
        sPrice: "$52.00",
        stars: ["./assets/images/star.png", "./assets/images/star.png", "./assets/images/star.png",  "./assets/images/star.png", "./assets/images/star-dark.png"],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        imgUrl: "./assets/images/content_product5.png",
        heading: "Morbi sagittis",
        cPrice: "$26.00",
        sPrice: "$52.00",
        stars: ["./assets/images/star.png", "./assets/images/star.png", "./assets/images/star.png",  "./assets/images/star.png", "./assets/images/star-dark.png"],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        imgUrl: "./assets/images/content_product6.png",
        heading: "Ultricies venenatis",
        cPrice: "$26.00",
        sPrice: "$52.00",
        stars: ["./assets/images/star.png", "./assets/images/star.png", "./assets/images/star.png",  "./assets/images/star.png", "./assets/images/star-dark.png"],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
    {
        imgUrl: "./assets/images/content_product7.png",
        heading: "Scelerisque dignissim",
        cPrice: "$26.00",
        sPrice: "$52.00",
        stars: ["./assets/images/star.png", "./assets/images/star.png", "./assets/images/star.png",  "./assets/images/star.png", "./assets/images/star-dark.png"],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    },
]